blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),
    path("post/", views.PostLV.as_view(), name="post_list"),
    re_path(r"^post/(?P<slug>[-\w]+)/$", views.PostDV.as_view(), name="post_detail"),
    path("add/", views.PostCreateView.as_view(), name="add"),
    path("change/", views.PostChangeLV.as_view(), name="change"),
    path("update/<int:pk>/", views.PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete"),
    path("archive/", views.PostAV.as_view(), name="post_archive"),
    path("archive/<int:year>/", views.PostYAV.as_view(), name="post_year_archive"),
    path(
        "archive/<int:year>/<str:month>/",
        views.PostMAV.as_view(),
        name="post_month_archive",
    ),
    path(
        "archive/<int:year>/<str:month>/<int:day>",
        views.PostDAV.as_view(),
        name="post_day_archive",
    ),
    path("archive/today", views.PostTAV.as_view(), name="post_today_archive"),
    path("tag/", views.TagCloudTV.as_view(), name="tag_cloud"),
    path("tag/<str:tag>/", views.TaggedObjectLV.as_view(), name="tagged_object_list"),
    path("search/", views.SearchFormView.as_view(), name="search"),
]

bookmark/urls.py
from django.urls import path
from . import views

app_name = "bookmark"

urlpatterns = [
    path("", views.BookmarkLV.as_view(), name="index"),
    path("<int:pk>/", views.BookmarkDV.as_view(), name="detail"),
    path("add/", views.BookmarkCreateView.as_view(), name="add"),
    path("change/", views.BookmarkChangeLV.as_view(), name="change"),
    path("update/<int:pk>/", views.BookmarkUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.BookmarkDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("accounts/register/done/", UserCreateDoneTV.as_view(), name="register_done"),
    path("", HomeView.as_view(), name="home"),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),
    path("photo/", include("photo.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmark/models.py
from tkinter import CASCADE
from turtle import title
from django.db import models
from django.contrib.auth.models import User


class Bookmark(models.Model):
    title = models.CharField("TITLE", max_length=90, blank=False)
    description = models.TextField("DESCRIPTION", blank=True)
    url = models.URLField("URL", unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from config.views import OwnerOnlyMixin
from .models import Bookmark


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ["title", "url", "description"]
    success_url = reverse_lazy("bookmark:index")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = "bookmark/bookmark_change_list.html"

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ["title", "url", "description"]
    success_url = reverse_lazy("bookmark:index")


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy("bookmark:index")

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}

<h2>북마크 ({{ user }})</h2>
<div class="text-right"><a class="btn btn-outline-secondary" href="{% url 'bookmark:add' %}"><i class="fa fa-pencil"></i>&nbsp;&nbsp;작성하기</a></div>
<table class="table table-striped mt-1">
    <thead>
        <tr class="table-dark">
            <th>이름</th>
            <th>설명</th>
            <th>URL</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.title }}</a></td>
            <td>{{ object.description }} </td>
            <td class="">{{ object.url }} </td>
            <td><a href="{% url 'bookmark:update' object.id %}"><i class="fa fa-pencil"></i></a></td>
            <td><a href="{% url 'bookmark:delete' object.id %}"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post" class="card pt-3"> {% csrf_token %}
        <p class="px-5">{{ object }} 북마크를 삭제할까요?</p>
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-sm"/> 
    </form>

{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} bookmark_detail.html {% endblock %}
{% block content %}
    <body>
        <div id="content">
            <h1>{{ object.title }}</h1>
            <p><a href = "{{ object.url }}"> {{ object.url }} </a></p>
            <p>{{ object.description }}</p>
        </div>
    </body>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}bookmark_form.html{% endblock %}

{% block content %}

    <h1>Bookmark Creation/Update</h1>
    <p class="font-italic">북마크를 생성/수정합니다.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-blod">아래에 에러를 확인하세요.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3"> {% csrf_token %}
        <div class="form-group row mb-2">
            {{ form.title|add_label_class:'col-form-label col-sm-2 ml-3 text-center'}}
            <div class="col-sm-5">
                {{ form.title|add_class:'form-control'|attr:'autofocus' }}
            </div>
        </div>
        <div class="form-group row mb-2">
            {{ form.url|add_label_class:'col-form-label col-sm-2 ml-3 text-center' }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group row mb-2">
            {{ form.description|add_label_class:'col-form-label col-sm-2 ml-3 text-center' }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group mb-2">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-secondary"/>
            </div>
        </div>
    </form>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} bookmark_list.html {% endblock %}
{% block content %}
    <body>
        <div id="content">
            <h1>북마크 목록</h1>
            <ul>
                {% for object in object_list %}
                    <li>
                        <a href = "{% url 'bookmark:detail' object.id %}"> {{ object.title }} </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </body>
{% endblock %}