blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),
    path("post/", views.PostLV.as_view(), name="post_list"),
    re_path(r"^post/(?P<slug>[-\w]+)/$", views.PostDV.as_view(), name="post_detail"),
    path("add/", views.PostCreateView.as_view(), name="add"),
    path("change/", views.PostChangeLV.as_view(), name="change"),
    path("update/<int:pk>/", views.PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete"),
    path("archive/", views.PostAV.as_view(), name="post_archive"),
    path("archive/<int:year>/", views.PostYAV.as_view(), name="post_year_archive"),
    path(
        "archive/<int:year>/<str:month>/",
        views.PostMAV.as_view(),
        name="post_month_archive",
    ),
    path(
        "archive/<int:year>/<str:month>/<int:day>",
        views.PostDAV.as_view(),
        name="post_day_archive",
    ),
    path("archive/today", views.PostTAV.as_view(), name="post_today_archive"),
    path("tag/", views.TagCloudTV.as_view(), name="tag_cloud"),
    path("tag/<str:tag>/", views.TaggedObjectLV.as_view(), name="tagged_object_list"),
    path("search/", views.SearchFormView.as_view(), name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("accounts/register/done/", UserCreateDoneTV.as_view(), name="register_done"),
    path("", HomeView.as_view(), name="home"),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),
    path("photo/", include("photo.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(verbose_name="TITLE", max_length=90)
    slug = models.SlugField(
        "SLUG", unique=True, allow_unicode=True
    )  # allow_unicode => 한글처리 가능
    description = models.CharField("DESCRIPTION", max_length=150, blank=True)
    content = models.TextField("CONTENT")
    create_dt = models.DateTimeField("CREATED DATE", auto_now_add=True)
    modify_dt = models.DateTimeField("MODIFIED DATE", auto_now=True)
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="OWNER", blank=True, null=True
    )

    class Meta:
        verbose_name = "post"
        verbose_name_plural = "posts"
        db_table = "blog_posts"
        ordering = ("-modify_dt",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="Search Word")

blog/views.py
from taggit.models import Tag
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views.generic.dates import (
    ArchiveIndexView,
    YearArchiveView,
    MonthArchiveView,
    DayArchiveView,
    TodayArchiveView,
)
from config.views import OwnerOnlyMixin
from .models import Post
from .forms import PostSearchForm


class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html"
    context_object_name = "posts"
    paginate_by = 5


class PostDV(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["disqus_short"] = f"{settings.DISQUS_SHORTNAME}"
        context["disqus_id"] = f"post-{self.object.id}-{self.object.slug}"
        context[
            "disqus_url"
        ] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context["disqus_title"] = f"{self.object.slug}"
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "description", "content", "tags"]
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = "blog/post_change_list.html"

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ["title", "description", "content", "tags"]
    success_url = reverse_lazy("blog:index")


class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog:index")


class PostAV(ArchiveIndexView):
    model = Post
    date_field = "modify_dt"


class PostYAV(YearArchiveView):
    model = Post
    date_field = "modify_dt"
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = "modify_dt"


class PostDAV(DayArchiveView):
    model = Post
    date_field = "modify_dt"


class PostTAV(TodayArchiveView):
    model = Post
    date_filed = "modify_dt"


class TagCloudTV(TemplateView):
    tags = Tag.objects.all()
    context = {"tags": tags}
    template_name = "taggit/taggit_cloud.html"


class TaggedObjectLV(ListView):
    model = Post
    template_name = "taggit/taggit_post_list.html"

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get("tag"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tagname"] = self.kwargs["tag"]
        return context


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = "blog/post_search.html"

    def form_valid(self, form):
        search_word = form.cleaned_data["search_word"]
        post_list = Post.objects.filter(
            Q(title__icontains=search_word)
            | Q(description__icontains=search_word)
            | Q(content__icontains=search_word)
        ).distinct()
        context = {}
        context["form"] = form
        context["search_term"] = search_word
        context["object_list"] = post_list

        return render(self.request, self.template_name, context)

blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% load static %}
{% block title %} post_all.html {% endblock %}
{% block content %}
    <body>
        <h1>포스트 목록</h1>
        <br/>
        {% for post in posts %}
            <h3> 
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> 
            </h3>
            {{ post.modify_dt|date:"Y-m-d"}}
            <p> {{ post.description }} </p>
        {% endfor %}
        <div>
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
                {% endif %}
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
                {% endif %}
            </span>
        </div>
    </body>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}
{% load static %}
{% block title %} post_archive.html {% endblock %}
{% block content %}
    <body>
        <h1>Post Archives until {% now "Y-m-d" %}</h1>
        <ul>
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">{{ date|date:"Y" }}년</a>
                </li>
            {% endfor %}
        </ul>
        <br/>
        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li> 
                {% endfor %}
            </ul>
        </div>
    </body>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}
{% load static %}
{% block title %} post_archive_day.html {% endblock %}
{% block content %}
    <body>
        <h1>Post Archives for {{ day|date:"Y-m-d" }}</h1>
        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li> 
                {% endfor %}
            </ul>
        </div>
    </body>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}
{% load static %}
{% block title %} post_archive_month.html {% endblock %}
{% block content %}
    <body>
        <h1>Post Archives for {{ month|date:"Y-m" }}</h1>
        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li> 
                {% endfor %}
            </ul>
        </div>
    </body>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}
{% load static %}
{% block title %} post_archive_year.html {% endblock %}
{% block content %}
    <body>
        <h1>Post Archives for {{ year|date:"Y" }}</h1>
        <ul>
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url "blog:post_month_archive" year|date:"Y" date|date:"b" %}">{{ date | date:"Y" }}년</a>
                </li>
            {% endfor %}
        </ul>
        <br/>
        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li> 
                {% endfor %}
            </ul>
        </div>
    </body>
{% endblock %}

blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}post_change_list.html{% endblock %}

{% block content %}

<h1>포스트 ({{ user }})</h1>
<div class="text-right"><a class="btn btn-outline-secondary" href="{% url 'blog:add' %}"><i class="fa fa-pencil"></i>&nbsp;&nbsp;작성하기</a></div>
<table class="table table-striped mt-1">
    <thead>
        <tr class="table-dark">
            <th>Title</th>
            <th>Description</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.title }}</a></td>
            <td>{{ object.description }} </td>
            <td><a href="{% url 'blog:update' object.id %}"><i class="fa fa-pencil"></i></a></td>
            <td><a href="{% url 'blog:delete' object.id %}"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Post Delete</h1>
    <br>

    <form action="." method="post" class="card pt-3"> {% csrf_token %}
        <p class="px-5">{{ object }} 포스트를 삭제할까요?</p>
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-sm"/> 
    </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} post_detail.html {% endblock %}
{% block content %}
    <body>
        <h2>{{ object.title }}</h2>
        <p> {{ object.modify_dt|date:"Y-m-d"}} </p>
        <br>
        <div>
            {{ object.content|linebreaks }}
        </div>
        <br>
        <div>
            <b>TAGS</b> <i class="fas fa-tag"></i>
            {% load taggit_templatetags2_tags %} 
            {% for tag in object.tags.all %}
                <a href="{% url 'blog:tagged_object_list' tag.name %}" class="btn btn-outline-secondary btn-sm">{{tag.name}}</a>
            {% endfor %}
            &emsp;
            <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-dark btn-sm">TagCloud</span></a>
        </div>
        <br>
        <p>
            {% if object.get_previous %}
                <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
                    {{ object.get_previous }} 
                </a>
            {% endif %}
            &laquo;-- || --&raquo;
            {% if object.get_next %}
                <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
                    {{ object.get_next }} 
                </a>
            {% endif %}
        </p>
        <br>
        <div id="disqus_thread"></div>
    </body>
{% endblock %}
{% block extra-script %}
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://pydjango-moon.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}post_form.html{% endblock %}

{% block content %}

    <h1>Post Creation/Update</h1>
    <p class="font-italic">포스트를 작성/수정합니다.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-blod">아래에 에러를 확인하세요.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3"> {% csrf_token %}
        <div class="form-group row mb-2">
            {{ form.title|add_label_class:'col-form-label col-sm-2 ml-3 text-center'}}
            <div class="col-sm-5">
                {{ form.title|add_class:'form-control'|attr:'autofocus' }}
            </div>
        </div>
        <div class="form-group row mb-2">
            {{ form.description|add_label_class:'col-form-label col-sm-2 ml-3 text-center' }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group row mb-2">
            {{ form.content|add_label_class:'col-form-label col-sm-2 ml-3 text-center' }}
            <div class="col-sm-5">
                {{ form.content|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group row mb-2">
            {{ form.tags|add_label_class:'col-form-label col-sm-2 ml-3 text-center' }}
            <div class="col-sm-5">
                {{ form.tags|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group mb-2">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-secondary"/>
            </div>
        </div>
    </form>

{% endblock %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}
{% block title %} post_search.html {% endblock %}
{% block content %}
<h1>Blog Search</h1>
<br>
<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-dark brn-sm">
</form>

<br/><br/>

{% if object_list %}
{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_dt|date:"Y-m-d"}}
    <p>{{ post.description }}</p>
{% endfor %}

{% elif search_term %}
    <b><i>Search for '{{ search_term }}' Not Found.</i></b>
{% endif %}
{% endblock %}