blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),
    path("post/", views.PostLV.as_view(), name="post_list"),
    re_path(r"^post/(?P<slug>[-\w]+)/$", views.PostDV.as_view(), name="post_detail"),
    path("add/", views.PostCreateView.as_view(), name="add"),
    path("change/", views.PostChangeLV.as_view(), name="change"),
    path("update/<int:pk>/", views.PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete"),
    path("archive/", views.PostAV.as_view(), name="post_archive"),
    path("archive/<int:year>/", views.PostYAV.as_view(), name="post_year_archive"),
    path(
        "archive/<int:year>/<str:month>/",
        views.PostMAV.as_view(),
        name="post_month_archive",
    ),
    path(
        "archive/<int:year>/<str:month>/<int:day>",
        views.PostDAV.as_view(),
        name="post_day_archive",
    ),
    path("archive/today", views.PostTAV.as_view(), name="post_today_archive"),
    path("tag/", views.TagCloudTV.as_view(), name="tag_cloud"),
    path("tag/<str:tag>/", views.TaggedObjectLV.as_view(), name="tagged_object_list"),
    path("search/", views.SearchFormView.as_view(), name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("accounts/register/done/", UserCreateDoneTV.as_view(), name="register_done"),
    path("", HomeView.as_view(), name="home"),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),
    path("photo/", include("photo.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from . import views

app_name = "photo"

urlpatterns = [
    path("", views.AlbumLV.as_view(), name="index"),
    path("album/", views.AlbumLV.as_view(), name="album_list"),
    path("album/<int:pk>/", views.AlbumDV.as_view(), name="album_detail"),
    path("photo/<int:pk>/", views.PhotoDV.as_view(), name="photo_detail"),
]

photo/models.py
from pydoc import describe
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from photo.fields import ThumbnailImageField


class Album(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField("One Line Description", max_length=100, blank=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="OWNER", blank=True, null=True
    )

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("photo:album_detail", args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField("TITLE", max_length=40)
    description = models.TextField("Photo Description", blank=True)
    image = ThumbnailImageField(upload_to="photo/%Y/%m")
    upload_dt = models.DateTimeField("Upload Date", auto_now_add=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="OWNER", blank=True, null=True
    )

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("photo:photo_detail", args=(self.id,))

photo/views.py
from django.views.generic import ListView, DetailView
from .models import Album, Photo


class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo

photo/templates/photo/album_detail.html
{% extends 'base.html' %}
{% block title %}album_detail.html{% endblock %}
{% block extra-style %}
<style>
    .thumbnail {border: 5px solid #ccc}
</style>
{% endblock %}

{% block content %}


    <div class="mt-5">
        <span class="h2">{{ object.name }}</span>&emsp;    
        <span class="font-italic h5">{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">
    
    <div class="row">
        {% for photo in object.photo_set.all %}
            <div class="col-md-3 mb-5">
                <div class="thumbnail">
                    <a href = "{{ photo.get_absolute_url }}">
                        <img src = "{{ photo.image.thumb_url }}" style="width: 100%;">
                    </a>
                </div>
                <ul>
                    <li class="font-italic">{{ photo.title }}</li>
                    <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
                </ul>
            </div>
        {% endfor %}
    </div>

{% endblock %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}
{% block title %}album_list.html{% endblock %}
{% block extra-style %}
<style>
    .thumbnail {border: 3px solid #ccc}
</style>
{% endblock %}

{% block content %}

    {% for object in object_list %}
        <div class="mt-5">
            <a class="h2" href="{% url 'photo:album_detail' object.id %}">
                {{ object.name }} 
            </a>&emsp;
            <span class="font-italic h5">{{ object.description }} </span>
        </div>
        <hr style="margin: 0 0 20px 0;">
        <div class="row">
            {% for photo in object.photo_set.all|slice:':5' %}
                <div class="ml-5">
                    <div class="thumbnail">
                        <a href = "{{ photo.get_absolute_url }}">
                            <img src = "{{ photo.image.thumb_url }}">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}

{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}photo_detail.html{% endblock %}

{% block content %}

    <h2 class="mt-5">{{ object.name }}</h2>
    
    <div class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 100%;">
            </a>
        </div>

        <ul class="col-md-3 mt-3">
            <li class="h5">Photo Description</li>
                {% if object.description %}
                    <p>{{ object.description|linebreaks }}</p>
                {% else %}
                    <p>(blank)</p>
                {% endif %}
            <li class="h5">Date Uploaded</li>
                <p class="font-italic">{{ object.upload_dt }}</p>
            <li class="h5">Album Name</li>
                <p class="font-italic">
                    <a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a>
                </p>
        </ul>
    </div>
    
{% endblock %}