blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),
    path("post/", views.PostLV.as_view(), name="post_list"),
    re_path(r"^post/(?P<slug>[-\w]+)/$", views.PostDV.as_view(), name="post_detail"),
    path("add/", views.PostCreateView.as_view(), name="add"),
    path("change/", views.PostChangeLV.as_view(), name="change"),
    path("update/<int:pk>/", views.PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete"),
    path("archive/", views.PostAV.as_view(), name="post_archive"),
    path("archive/<int:year>/", views.PostYAV.as_view(), name="post_year_archive"),
    path(
        "archive/<int:year>/<str:month>/",
        views.PostMAV.as_view(),
        name="post_month_archive",
    ),
    path(
        "archive/<int:year>/<str:month>/<int:day>",
        views.PostDAV.as_view(),
        name="post_day_archive",
    ),
    path("archive/today", views.PostTAV.as_view(), name="post_today_archive"),
    path("tag/", views.TagCloudTV.as_view(), name="tag_cloud"),
    path("tag/<str:tag>/", views.TaggedObjectLV.as_view(), name="tagged_object_list"),
    path("search/", views.SearchFormView.as_view(), name="search"),
]

bookmark/urls.py
from django.urls import path
from . import views

app_name = "bookmark"

urlpatterns = [
    path("", views.BookmarkLV.as_view(), name="index"),
    path("<int:pk>/", views.BookmarkDV.as_view(), name="detail"),
    path("add/", views.BookmarkCreateView.as_view(), name="add"),
    path("change/", views.BookmarkChangeLV.as_view(), name="change"),
    path("update/<int:pk>/", views.BookmarkUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.BookmarkDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("accounts/register/done/", UserCreateDoneTV.as_view(), name="register_done"),
    path("", HomeView.as_view(), name="home"),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),
    path("photo/", include("photo.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from . import views

app_name = "photo"

urlpatterns = [
    path("", views.AlbumLV.as_view(), name="index"),
    path("album/", views.AlbumLV.as_view(), name="album_list"),
    path("album/<int:pk>/", views.AlbumDV.as_view(), name="album_detail"),
    path("photo/<int:pk>/", views.PhotoDV.as_view(), name="photo_detail"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Moon's WebService{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
        {% block extra-style %} {% endblock %}
    </head>

    <body style="padding-top:90px;">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <a class="navbar-brand mx-5 mb-0 font-weight-bold font-italic" href="{% url 'home' %}">Django Web Programming</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mx-1 btn btn-dark">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-dark">
                        <a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-dark">
                        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-dark">
                        <a class="nav-link" href="{% url 'photo:index' %}">Photo</a>
                    </li>
                    <li class="nav-item dropdown mx-2 btn btn-dark">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Util
                        </a>
                        <ul class="dropdown-menu">    
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                            <li><hr class="dropdown-divider"></li>
                            {% if request.user.is_active %}                 
                            <li><a class="dropdown-item" href="{% url 'bookmark:change' %}">Edit My Bookmarks</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:change' %}">Edit My Posts</a></li>
                            <li><hr class="dropdown-divider"></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Post Archive</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:search' %}">Post Search</a></li>
                        </ul>
                    </li>
                </ul>

                <form class="form-inline my-2" method="post"> {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
                </form>

                <div class="navbar-nav ml-5 mr-5">
                    <div class="nav-item dropdown mx-3 btn btn-dark">
                        {% if user.is_active %}
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user"></i>&ensp;
                            {% firstof user.get_short_name user.get_username %}&ensp;
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                            <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                        </ul>
                        {% else %}
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                        </ul>
                        {% endif %}
                    </div>
                </div>

            </div>
        </nav>

        <div class="container">
            {% block content %} {% endblock %}
        </div>

        {% block footer %} {% endblock %}
        
        <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"></script>
        <script src="https://kit.fontawesome.com/c53b730126.js" crossorigin="anonymous"></script>
        {% block extra-script %} {% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Home {% endblock %}

{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'img/home.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
</style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
</div>    

<hr style="margin: 10px 0;">

<div class="row">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>Bookmark is a URI(Uniform Resource Identifier) that is stored for later retrieval in 
            any of various storage formats. You can store your own bookmarks by Bookmark application.
            It is als possible to update or delete your bookmarks.
        </p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>This application makes it possible to log daily events or write your own interests
            such as hobbies, techniques, etc. A typical blog combines text, digital images, and
            links to other blogs, web pages, and other media related to its topic.
        </p>
    </div>
</div>
{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-dark">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2022 Django Project by Moon</div>
</footer>
{% endblock %}